### ISSUE TITLE
Request + renew cron mode

### ISSUE THREAD

**Issue by realies** [horjulf/docker-certbot_cloudflare#1]
It would be great if the container can be started in request and if successful renew cron mode. This would make it easier to deploy with a single command.

**Comment by horjulf** [comment]
The idea is that it runs once a week, so setting a cron job from the OS level to run the container makes more sense than keeping the container running/sleeping for so long without doing anything.

**Comment by realies** [comment]
The idea behind Docker containers is to minimise configuration and maintenance, requesting a new certificate if none exist followed by an automatical renewal management would make this image easier to use.

**Comment by horjulf** [comment]
Thats not supported by `certbot` and would require a wrapper. Its not the object of this image.
Feel free to fork the repo and customize it to your needs.
