### ISSUE TITLE
Add support for wildcards

### ISSUE THREAD

**Issue by realies** [horjulf/docker-certbot_cloudflare#2]
Getting `The currently selected ACME CA endpoint does not support issuing wildcard certificates.` when trying to obtain a *.domain.com certificate.

**Comment by horjulf** [comment]
The container just exposes the official `certbot` while adding the cloudflare plugin.

From the official documentation:
```
If you would like to obtain a wildcard certificate from Let’s Encrypt’s ACMEv2 server, you’ll need to include --server https://acme-v02.api.letsencrypt.org/directory on the command line as well.
```

Let me know if it works.

**Comment by horjulf** [comment]
Thats not supported by `certbot` and would involve adding a wrapper, its not the objective of this image.
Feel free to fork the repo and customize it to your needs.
